// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysrDKlAwESvJe8s40KpaR8nTWFAhO378',
    appId: '1:383630810032:android:140452c2ebb44627429475',
    messagingSenderId: '383630810032',
    projectId: 'sekolah-app-657d7',
    storageBucket: 'sekolah-app-657d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9bMOwnAkKcaNBqwxwLlR_u4EKtdQbZHI',
    appId: '1:383630810032:ios:9e0d85fd4b03220e429475',
    messagingSenderId: '383630810032',
    projectId: 'sekolah-app-657d7',
    storageBucket: 'sekolah-app-657d7.appspot.com',
    iosBundleId: 'com.wismoon.sekolahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBajkdXLhZ7x62wV6dLkAR7H61kgl45xD0',
    appId: '1:383630810032:web:cd88e2e22195c102429475',
    messagingSenderId: '383630810032',
    projectId: 'sekolah-app-657d7',
    authDomain: 'sekolah-app-657d7.firebaseapp.com',
    storageBucket: 'sekolah-app-657d7.appspot.com',
  );
}
